export const VAULT_COMPARE_RESULT_COPY = {
  aiVerified: 'AI Verified',
  targetRole: 'Target Role',
  targetRoleUnset: 'General comparison',
  exportReport: 'Export Report',
  promote: 'Promote',
  analysisTitle: 'AI Difference Analysis',
  recommendationReason: 'Recommendation Reason',
  onlyInVersion: (version: number) => `Only in v${version}`,
  uniqueSectionA: 'Unique to this version',
  uniqueSectionB: 'Added / rewritten in this version',
  rewritten: 'Rewritten',
  viewAllDifferences: 'View all differences',
  hideAllDifferences: 'Hide details',
  noSectionChanges: 'No changes in this section.',
  score: 'Score',
  openDetail: 'Open Detail',
  modified: 'Modified',
  recommended: 'RECOMMENDED',
  resumeA: 'Resume A',
  resumeB: 'Resume B',
  version: 'Version',
  versionLabel: (version: number) => `Version ${version}`,
  promoting: 'Promoting…',
  promoteSuccess: (version: number) => `Version ${version} promoted to current head`,
  promoteFailed: 'Failed to promote version',
  exportSuccess: 'Report downloaded',
  none: 'None',
  noComparisonTitle: 'No comparison loaded',
  noComparisonBody: 'Open the comparison lab and pick two resume versions to compare.',
  backToCompare: 'Back to Compare',
} as const;

