export const VAULT_LIBRARY_COPY = {
  eyebrow: 'Resume Vault',
  title: 'My Library',
  subtitle: 'Manage and optimize your tailored resumes.',
  filter: 'Filter',
  upload: 'Upload',
  loading: 'Loading your library…',
  retry: 'Try again',
  emptyTitle: 'No resumes yet',
  emptyBody: 'Upload your first resume to start building tailored variants for each role.',
  emptyActiveFilter: 'No active resume is set yet.',
  emptyAction: 'Upload a resume',
  footerTip: 'Keep variations of your resume to match specific job families.',
  activeBadge: 'Active',
  columns: {
    documentName: 'Document Name',
    version: 'Version',
    aiScore: 'AI Score',
    tags: 'Tags',
    actions: 'Actions',
  },
  filterPanel: {
    showLabel: 'Show',
    sortLabel: 'Sort by',
    all: 'All resumes',
    activeOnly: 'Active only',
    sortUpdated: 'Recently updated',
    sortName: 'Name',
    sortScore: 'AI score',
  },
  rowMenu: {
    open: 'Open resume',
    setActive: 'Set as active',
    delete: 'Delete resume',
  },
} as const;
