export const VAULT_VERSIONS_COPY = {
  loading: 'Loading versions…',
  retry: 'Retry',
  emptyTitle: 'No versions yet',
  empty: 'Upload a new version from the resume hub to start building history.',
  notFound: 'Resume not found',
  backToLibrary: 'Back to Library',
  invalidResume: 'Invalid resume',
  compatScore: 'Compat Score',
  active: 'ACTIVE',
  currentHead: 'CURRENT HEAD',
  editDetails: 'Edit Details',
  newVersion: 'New Version',
  created: 'Created',
  filename: 'Filename',
  atsScore: 'ATS Score',
  userNote: 'User Note',
  noUserNote: 'No note added.',
  aiDiffSummary: 'AI Diff Summary',
  noDiffSummary: 'No AI summary available for this version.',
  preview: 'Preview',
  pdf: 'PDF',
  compare: 'Compare',
  restore: 'Restore',
  restoring: 'Restoring…',
  downloading: 'Downloading…',
  comparing: 'Comparing…',
} as const;
