export const COMPANY_OPTIONS = [
  'Google',
  'Microsoft',
  'Amazon',
  'Meta',
  'Apple',
  'Netflix',
  'Uber',
  'Airbnb',
  'Stripe',
  'Atlassian',
  'Salesforce',
  'Adobe',
  'Oracle',
  'IBM',
  'Nvidia',
  'Tesla',
  'OpenAI',
  'Anthropic',
  'Databricks',
  'Snowflake',
  'Palantir',
  'Bloomberg',
  'Goldman Sachs',
  'JPMorgan Chase',
  'Walmart Global Tech',
  'Flipkart',
  'PhonePe',
  'Razorpay',
  'Zomato',
  'Swiggy',
  'CRED',
  'Meesho',
  'Zoho',
  'Freshworks',
  'TCS',
  'Infosys',
  'Wipro',
  'Accenture',
  'Deloitte',
] as const;

export const ROLE_OPTIONS = [
  'Software Engineer',
  'Frontend Engineer',
  'Backend Engineer',
  'Full Stack Engineer',
  'Mobile Engineer',
  'Android Engineer',
  'iOS Engineer',
  'DevOps Engineer',
  'Site Reliability Engineer',
  'Cloud Engineer',
  'Platform Engineer',
  'Data Engineer',
  'Machine Learning Engineer',
  'AI Engineer',
  'Data Scientist',
  'Data Analyst',
  'Product Engineer',
  'QA Engineer',
  'Security Engineer',
  'System Design / Architecture',
  'Engineering Manager',
  'Product Manager',
  'Technical Program Manager',
  'Business Analyst',
] as const;
